- name: Deploy containerd-config
  ansible.builtin.copy:
    src: containerd_config.toml
    dest: /etc/containerd/config.toml
    mode: u=rw,g=r,o=r

- name: restart_containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
