- name: Install K3s agent
  command: /root/k3s_install.sh {{ type }}
  register: command
  changed_when: "'No change detected' not in command.stdout"
  until: "command is not failed"
  retries: 2
  delay: 10

- name: Restart when config changed, but install already done
  service:
    name: k3s
    status: restarted
  when: "inventory_hostname != groups['kubernetes'][0] and not command.changed and config.changed"
