- name: Install K3s agent
  command: /root/k3s_install.sh {{ type }}
  register: command
  changed_when: "'No change detected' not in command.stdout"
  until: "command is not failed"
  retries: 2
  delay: 10

- name: Make sure service is started / restarted on config change
  service:
    name: k3s-agent
    state: "{{ 'restarted' if not command.changed and config.changed else 'started' }}"
