- name: Install nftables
  package:
    name:
      - nftables

- name: Create /etc/nftables/ansible-managed
  file:
    path: /etc/nftables/ansible-managed
    state: directory

- name: Include files in /etc/nftables/ansible-managed/ from /etc/nftables.conf
  blockinfile:
    path: /etc/nftables.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - nftables"
    content: 'include "/etc/nftables/ansible-managed/*.nft"'
