- name: Load br_netfilter kernel-module
  modprobe:
      name: br_netfilter
      state: present

- name: Set sysctl settings for iptables bridged traffic
  copy:
      dest: "/etc/sysctl.d/kubernetes.conf"
      content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
  notify: reload_sysctl

-  import_tasks: ./prerequisites/swap.yml

-  import_tasks: ./prerequisites/containerd.yml

- name: Set control-plane-dns-endpoint towards local-ip
  lineinfile:
      dest: /etc/hosts
      line: "{{ ansible_facts.default_ipv6.address }} k8s-control-plane.system.ruekov.eu" 
