- name: Join netmaker-network
  when: "netclient.join_network_token is defined"
  command: "netclient join -t {{ netclient.join_network_token }}"
  failed_when: command.rc != 0
  changed_when: "'starting wireguard' in command.stdout"
  register: command
  throttle: 1
