- name: Update Packages
  apt:
      update_cache: yes
      upgrade: yes
  when: ansible_facts.distribution == "Debian"

- name: Install Packages
  package:
      name:
          - gpg
          - htop
          - iotop
          - slurm
          - sudo
          - screen
          - curl
          - rsync
          - zstd
      state: latest
  when: ansible_facts.distribution == "Debian"
