---
kubernetes:
  ipPool:
    ipv4:
      cluster_cidr: 10.42.0.0/16
      service_cidr: 10.43.0.0/16
      nodeip_cidr: 10.41.0.0/24
    ipv6:
      cluster_cidr: fd42::/56
      service_cidr: fd43::/112
      nodeip_cidr: fd41::/64

  control_plane:
    dns_name: <control-plane dns-reachable-name>

  shared_token: <shared token for nodes to join>
