- name: Deploy service
  ansible.builtin.template:
    src: wg-ipv6-conv.service.jinja2
    dest: /etc/systemd/system/wg-ipv6-converter_{{ wireguard_ipv6_converter.setup.interface }}.service
  register: serviceFile

- name: Enable & Start service
  ansible.builtin.service:
    name: wg-ipv6-converter_{{ wireguard_ipv6_converter.setup.interface }}
    state: "{{ 'restarted' if serviceFile.changed else 'started' }}"
    enabled: true

