- name: Add Balto key
  apt_key:
      url: https://baltocdn.com/helm/signing.asc
      state: present

- name: Add Balto Repository
  apt_repository:
      repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
      state: present
      filename: kubernetes
      update_cache: yes

- name: Install helm
  package:
      name:
          - helm
      state: latest
