- name: Deploying group files
  include_tasks: ./per-group-template-file.yml
  with_items:
    - "{{ nftables.rules.files | list }}"

- name: Deploying group raw-files
  include_tasks: ./per-group-template.yml
  with_items:
    - "{{ nftables.rules.raw | list }}"

- include_tasks: ./remove-files.yml
